name: test and deploy

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0

      - name: Build Rust for WASM
        run: wasm-pack build

      - name: Test WASM on Firefox
        run: wasm-pack test --firefox --headless

      - name: Test WASM on Chrome
        run: wasm-pack test --chrome --headless

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Node Modules
        run: npm ci
        working-directory: ./www

      - name: Build Js
        run: npm run build --if-present
        working-directory: ./www

      - name: Deploy To Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./www/dist
